# Generated by Django 4.2.8 on 2024-05-02 01:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("information_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="is archived"),
        ),
    ]
