# Generated by Django 4.2.8 on 2024-05-13 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("information_assets", "0003_alter_asset_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ("name", "owner"),
                "permissions": (("archive_asset", "Can archive asset"),),
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
            },
        ),
    ]
