# Generated by Django 4.2.13 on 2024-06-07 16:48

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models

import base.mixins


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("information_assets", "0006_assetrole"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRoleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_role_users",
                        to="information_assets.assetrole",
                        verbose_name="role",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_role_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "asset role user",
                "verbose_name_plural": "asset role users",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
        migrations.AddField(
            model_name="assetrole",
            name="users",
            field=models.ManyToManyField(
                related_name="asset_roles",
                through="information_assets.AssetRoleUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
    ]
