# Generated by Django 4.2.13 on 2024-06-13 13:40

import django.db.models.deletion

from django.db import migrations
from django.db import models


def apply_migration(apps, schema_editor):
    Asset = apps.get_model("information_assets", "Asset")

    for asset in Asset.objects.all():
        asset.asset_types.set((asset.asset_type,))


def revert_migration(apps, schema_editor):
    Asset = apps.get_model("information_assets", "Asset")

    for asset in Asset.objects.all():
        asset.asset_type = asset.asset_types.first()
        asset.save()


class Migration(migrations.Migration):
    dependencies = [
        ("information_assets", "0007_assetroleuser_assetrole_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_types",
            field=models.ManyToManyField(
                related_name="assets",
                to="information_assets.assettype",
                verbose_name="types",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="information_assets.assettype",
                verbose_name="type",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
        migrations.RemoveField(
            model_name="asset",
            name="asset_type",
        ),
    ]
