# Generated by Django 4.2.8 on 2024-05-14 11:45

from django.db import migrations


def remove_users_group_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="users", content_type__model="group"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"default_permissions": ()},
        ),
        migrations.RunPython(remove_users_group_permissions, migrations.RunPython.noop),
    ]
