repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff --fix
        language: system
        types:
          - python
        stages:
          - commit

      - id: black
        name: reformat code with black
        entry: poetry run black
        types:
          - python
        language: system
        stages:
          - commit

      - id: health-check
        name: health check
        entry: poetry run python manage.py check --fail-level WARNING
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - commit

      - id: migrations
        name: check migrations
        entry: poetry run python3 manage.py makemigrations --check --dry-run
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - push

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
        stages:
          - commit
      - id: djlint-reformat-django
        stages:
          - commit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trim trailing whitespace
        types_or:
          - pug
          - markdown
        stages:
          - commit

      - id: end-of-file-fixer
        name: end files with a single newline
        types_or:
          - pug
          - markdown
        stages:
          - commit
