version: '3'
services:
  postgres:
    image: "postgres:14-alpine"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-pgdata:/var/lib/postgresql/data/pgdata
  django:
    build:
      context: .
      target: production
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-pgdata:
