version: '3'
services:
  postgres:
    image: "postgres:14-alpine"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-pgdata:/var/lib/postgresql/data/pgdata
      - ./db_dumps:/db_dumps
  django:
    build:
      context: .
      target: production
    env_file: .env
    environment:
      # To be set in this container only, so the postgres container still uses the passwordless socket.
      PGHOST: $POSTGRES_HOST
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - static:/usr/src/app/project/static
      - ./project/media:/usr/src/app/project/media

volumes:
  postgres-pgdata:
  static:
