version: '3'
services:
  # Note: don't change service names as they are hardcoded in other places.

  postgres:
    build: ./docker/postgres/
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./db_dumps:/db_dumps

  django:
    build:
      context: .
      target: production
    env_file: .env
    depends_on:
      - postgres
    init: yes
    restart: unless-stopped
    volumes:
      - static:/usr/src/app/project/static
      - ./project/media:/usr/src/app/project/media

volumes:
  postgres-data:
  static:
