version: '3'
services:
  postgres:
    image: "postgres:14-alpine"
    env_file:
      - docker/development.env
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-pgdata:/var/lib/postgresql/data/pgdata
  django:
    build: .
    env_file:
      - docker/development.env
    network_mode: "host"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app

volumes:
  postgres-pgdata:
