[tool.poetry]
name = "django3-project-template"
version = "0.1.0"
description = "A project template for Django 3.2. This project tries to solve problems or features that commonly appear on Magnet projects. The idea is that you start your project using this code as the base."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9.9"
django = "~3.2.11"
psycopg2 = "~2.9.3"
django-storages = "~1.12.3"
black = "21.12b0"
ipython = "8.0.0"
gunicorn = "~20.1.0"
pytz = ">=2021.3"
django-debug-toolbar = "3.2.4"
pypugjs = "5.9.10"
ipdb = "0.13.9"
django-loginas = "0.3.10"
djangorestframework = "~3.13.1"
djangorestframework-camel-case = "~1.3.0"
boto3 = "1.21.15"
inflection = "0.5.1"

[tool.poetry.dev-dependencies]
flake8 = "4.0.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"
ansible = "^5.3.0"
yq = "^2.14.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
