[tool.poetry]
name = "project-name-placeholder"
version = "0.1.0"
description = "The project template for Django 3.2. This project aims to provide a common starting point for Magnet projects."
authors = ["Magnet DPT3 Team <d3pt@magnet.cl>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.9.9"
# semver packages
django = "~3.2.13"
psycopg2 = "2.9.3"
gunicorn = "~20.1.0"
django-loginas = "0.3.10"
djangorestframework = "3.13.1"
boto3 = "1.23.0"
ipdb = "0.13.9"
ipython = "8.3.0"
ansible-core = { version = "2.13", optional = true }
yq = { version = "2.14.0", optional = true }
Faker = "13.12.1"
# non-semver packages (or no information found)
django-debug-toolbar = "3.4.0"
django-extensions = "3.1.5"
django-storages = "1.12.3"
django-webpack-loader = "1.5.0"
djangorestframework-camel-case = "1.3.0"
inflection = "0.5.1"
pymemcache = "3.5.2"
pypugjs = "5.9.11"
# calver packages that must be updated always
pytz = ">=2022.1"

[tool.poetry.dev-dependencies]
# semver packages
pytest = "7.1.2"
pytest-cov = "3.0.0"
pytest-django = "4.5.2"
flake8 = "4.0.1"
isort = "5.10.1"
pre-commit = "2.19.0"
watchdog = "2.1.8"
# calver packages
black = "22.3.0"
# Lock Werkzeug until django-extensions fixes their integration.
Werkzeug = "2.0.1"

[tool.poetry.extras]
ansible = ["ansible-core", "yq"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
ensure_newline_before_comments = true
extend_skip = ["migrations", "manage.py"]
filter_files = true
force_single_line = true
group_by_package = true
import_heading_django = "django"
import_heading_stdlib = "standard library"
import_heading_thirdparty = "others libraries"
known_django = "django"
lines_between_types = 1
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
required_plugins = "pytest-django"
DJANGO_SETTINGS_MODULE = "project.test_settings"
addopts = [
  "-v",
  "--tb=native",
  "--junit-xml=test-results/pytest.xml"
]
python_files = [
  "tests.py",
  "test_*.py",
  "*_tests.py"
]
junit_family = "xunit2"
