# Generated by Django 4.2.8 on 2024-04-10 13:22

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models

import base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("documents", "0005_alter_documentversion_shasum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="documents.control",
                        verbose_name="control",
                    ),
                ),
            ],
            options={
                "verbose_name": "process",
                "verbose_name_plural": "processes",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "recurrency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMIANNUALLY", "Semiannually"),
                            ("ANNUALLY", "Annually"),
                        ],
                        max_length=255,
                        verbose_name="recurrency",
                    ),
                ),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_definitions",
                        to="documents.control",
                        verbose_name="control",
                    ),
                ),
            ],
            options={
                "verbose_name": "process definition",
                "verbose_name_plural": "process definitions",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessActivityDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "asignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_definitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asignee",
                    ),
                ),
                (
                    "asignee_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activity_definitions",
                        to="auth.group",
                        verbose_name="asignee group",
                    ),
                ),
                (
                    "process_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_definitions",
                        to="processes.processdefinition",
                        verbose_name="process definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "process activity definition",
                "verbose_name_plural": "process activity definitions",
                "ordering": ("process_definition", "order"),
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="order")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "activity_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="processes.processactivitydefinition",
                        verbose_name="activity definition",
                    ),
                ),
                (
                    "asignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="asignee",
                    ),
                ),
                (
                    "asignee_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="auth.group",
                        verbose_name="asignee group",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completed_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="completed by",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities",
                        to="processes.process",
                        verbose_name="process",
                    ),
                ),
            ],
            options={
                "verbose_name": "process activity",
                "verbose_name_plural": "process activities",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
        migrations.AddField(
            model_name="process",
            name="process_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processes",
                to="processes.processdefinition",
                verbose_name="process definition",
            ),
        ),
        migrations.AddConstraint(
            model_name="processactivitydefinition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("asignee__isnull", False),
                    ("asignee_group__isnull", False),
                    _connector="XOR",
                ),
                name="asignee_xor_asignee_group",
            ),
        ),
    ]
