# Generated by Django 4.2.8 on 2024-04-10 15:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processactivitydefinition",
            name="asignee_xor_asignee_group",
        ),
        migrations.AddConstraint(
            model_name="processactivitydefinition",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("asignee__isnull", False),
                    ("asignee_group__isnull", False),
                    _connector="XOR",
                ),
                name="asignee_xor_asignee_group",
                violation_error_message="An activity definition must have an asignee or an asignee group, but not both.",
            ),
        ),
    ]
