# Generated by Django 4.2.8 on 2024-04-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "processes",
            "0002_remove_processactivitydefinition_asignee_xor_asignee_group_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processactivity",
            name="completed_by",
        ),
    ]
