# Generated by Django 4.2.8 on 2024-04-25 19:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0003_remove_evidence_document_version_evidence_url_and_more"),
        (
            "processes",
            "0002_alter_processactivity_options_remove_process_control_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processversion",
            options={
                "permissions": (
                    ("publish_processversion", "Can publish process version"),
                ),
                "verbose_name": "process version",
                "verbose_name_plural": "process versions",
            },
        ),
        migrations.AddField(
            model_name="processversion",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AddField(
            model_name="processversion",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="published at"
            ),
        ),
        migrations.AlterField(
            model_name="processversion",
            name="controls",
            field=models.ManyToManyField(
                related_name="process_versions",
                to="documents.control",
                verbose_name="controls",
            ),
        ),
    ]
