# Generated by Django 4.2.8 on 2024-04-29 16:53

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("processes", "0004_remove_processactivityinstance_asignee_group_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="processactivity",
            name="asignee_xor_asignee_group",
        ),
        migrations.RemoveField(
            model_name="processactivity",
            name="asignee",
        ),
        migrations.RenameField(
            model_name="processactivityinstance",
            old_name="completed",
            new_name="is_completed",
        ),
        migrations.RenameField(
            model_name="processinstance",
            old_name="completed",
            new_name="is_completed",
        ),
        migrations.AlterField(
            model_name="processactivity",
            name="asignee_group",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="auth.group",
                verbose_name="asignee group",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processactivityinstance",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
        migrations.AlterField(
            model_name="processinstance",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
    ]
