# Generated by Django 4.2.8 on 2024-05-09 13:16

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_group"),
        ("processes", "0006_rename_processactivity_asignee_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processactivity",
            name="assignee_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activities",
                to="users.group",
                verbose_name="assignee group",
            ),
        ),
    ]
