# Generated by Django 4.2.8 on 2024-05-16 19:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0007_alter_processactivity_assignee_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="processinstance",
            name="comment",
            field=models.TextField(blank=True, verbose_name="comment"),
        ),
        migrations.AddField(
            model_name="processversion",
            name="comment_label",
            field=models.CharField(
                blank=True, max_length=31, verbose_name="comment label"
            ),
        ),
    ]
