# Generated by Django 4.2.13 on 2024-06-03 21:33

import django.db.models.deletion

from django.db import migrations
from django.db import models


def apply_migration(apps, schema_editor):
    ProcessActivity = apps.get_model("processes", "ProcessActivity")

    for activity in ProcessActivity.objects.all():
        activity.assignee_groups.set([activity.assignee_group])


def revert_migration(apps, schema_editor):
    ProcessActivity = apps.get_model("processes", "ProcessActivity")

    for activity in ProcessActivity.objects.all():
        activity.assignee_group = activity.assignee_groups.first()
        activity.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_group_options"),
        ("processes", "0008_processinstance_comment_processversion_comment_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processactivity",
            name="assignee_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="users.group",
                verbose_name="assignee group",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processactivity",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="title"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processactivity",
            name="assignee_groups",
            field=models.ManyToManyField(
                related_name="activities",
                to="users.group",
                verbose_name="assignee groups",
            ),
        ),
        migrations.RunPython(apply_migration, revert_migration),
        migrations.RemoveField(
            model_name="processactivity",
            name="assignee_group",
        ),
    ]
