# Generated by Django 4.2.13 on 2024-06-11 16:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0009_processactivity_assignee_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processactivity",
            name="deliverables",
            field=models.TextField(blank=True, verbose_name="deliverables"),
        ),
    ]
