# Generated by Django 4.2.13 on 2024-06-12 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0010_processactivity_deliverables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processactivityinstance",
            options={
                "ordering": ("-pk",),
                "verbose_name": "process activity instance",
                "verbose_name_plural": "process activity instances",
            },
        ),
    ]
