# Generated by Django 4.2.13 on 2024-06-13 15:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0011_alter_processactivityinstance_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="processversion",
            name="email_to_notify_completion",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email to notify completion"
            ),
        ),
    ]
