# Generated by Django 4.2.8 on 2024-03-28 11:55

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models

import base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0003_alter_controlcategory_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("information_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Very Low"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        max_length=255,
                        verbose_name="severity",
                    ),
                ),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("VERY_LOW", "Very Low"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("VERY_HIGH", "Very High"),
                        ],
                        max_length=255,
                        verbose_name="likelihood",
                    ),
                ),
                (
                    "treatment",
                    models.CharField(
                        choices=[
                            ("MITIGATE", "Mitigate"),
                            ("TRANSFER", "Transfer"),
                            ("ACCEPT", "Accept"),
                            ("ELIMINATE", "Eliminate"),
                        ],
                        max_length=255,
                        verbose_name="treatment",
                    ),
                ),
                (
                    "assets",
                    models.ManyToManyField(
                        related_name="risks",
                        to="information_assets.asset",
                        verbose_name="asset",
                    ),
                ),
                (
                    "controls",
                    models.ManyToManyField(
                        related_name="risks",
                        to="documents.control",
                        verbose_name="control",
                    ),
                ),
                (
                    "residual_risks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="residual_risk_for",
                        to="risks.risk",
                        verbose_name="residual risk for",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="responsible",
                    ),
                ),
            ],
            options={
                "verbose_name": "risk",
                "verbose_name_plural": "risks",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
    ]
