# Generated by Django 4.2.8 on 2024-04-12 14:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="title"),
        ),
    ]
