# Generated by Django 4.2.13 on 2024-06-18 13:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0014_alter_documenttype_options"),
        ("risks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk",
            name="controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="risks",
                to="documents.control",
                verbose_name="control",
            ),
        ),
    ]
