services:
  django:
    healthcheck:
      test: ["CMD-SHELL", "wait-for-it localhost:8000 --timeout=5"]
      interval: 10s
      timeout: 6s
      start_period: 30s
    depends_on:
      - memcached

  nginx:
    image: jonasal/nginx-certbot:3.0.0-nginx1.21.3-alpine
    env_file: docker/nginx.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django  # To prevent '[emerg] host not found in upstream "django"'
    restart: unless-stopped
    volumes:
      - ./docker/nginx_templates/:/etc/nginx/templates/:ro
      - ./project/static/:/usr/share/nginx/static/:ro
      - ./project/media/:/usr/share/nginx/media/:ro
      - ./docker/volumes/nginx_secrets/:/etc/letsencrypt/

  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped
    command:
      - memcached
      - --memory-limit=${MEMCACHED_MEMORY}
      - --threads=${MEMCACHED_THREADS}
      # Uncomment to check for activity:
      # - -vv

volumes:
  nginx_secrets:
