version: "3.4"
services:
  db:
    image: "postgres:14-alpine"
    env_file: "ci_env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ../
      target: test
    env_file: "ci_env"
    depends_on:
      - db
