services:
  nginx:
    # TODO: certbot
    image: nginx:1.21-alpine
    env_file: docker/nginx.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./docker/nginx/default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: yes
      - static:/usr/share/nginx/static
      - ./project/media:/usr/share/nginx/media

  # TODO
  # memcached:
  # https://docs.djangoproject.com/en/3.2/topics/cache/#memcached
