version: "3.4"

# The following setup works around the limitation of bind mounts not allowed on
# CircleCI jobs. This problem can be resolved on two ways:
# - Using a machine executor
# - Tell remote docker to run two containers, sharing a common volume between
#   them.
# This compose file is based on the one implemented by Peter Bengtsson for
# Mozilla's Normandy. See:
# https://github.com/mozilla/normandy/blob/5eb2a4447ef3b6cf1b92c894d168b60702867eb4/ci/docker-compose.yml
services:
  db:
    image: "postgres:14-alpine"
    env_file: "ci_env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    image: app-test
    env_file: "ci_env"
    depends_on:
      - db
    volumes:
      - test-artifacts:/usr/src/app/test-results

  artifact-collector:
    image: busybox:stable
    volumes:
      - test-artifacts:/artifacts
    command: |
      sh -c "
        chmod -R 777 /artifacts
        echo Waiting for artifacts
        sleep 1h  # Wait a long time
      "

volumes:
  test-artifacts:
