services:
  django:
    healthcheck:
      test: ["CMD-SHELL", "wait-for-it localhost:8000 --timeout=5"]
      interval: 10s
      timeout: 6s
      start_period: 30s
    depends_on:
      - memcached
    volumes:
      - ./project/static/:/usr/src/app/project/static/
      - ./project/media/:/usr/src/app/project/media/
      # Keep histories:
      - ./docker/volumes/.zsh_history/:/home/${WHO}/.zsh_history/
      - ./docker/volumes/.ipython/:/home/${WHO}/.ipython/
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.django-cron.schedule: "@every 1m"
      # ofelia.job-exec.django-cron.command: dj runcrons
      ofelia.job-exec.django-cron.command: >
        dj shell -c "print('TODO: install either old django-cron or modern replacement')"

  nginx:
    build:
      context: ./docker/nginx/
    env_file: docker/nginx.env
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django  # To prevent '[emerg] host not found in upstream "django"'
    restart: unless-stopped
    volumes:
      - ./project/static/:/usr/share/nginx/static/:ro
      - ./project/media/:/usr/share/nginx/media/:ro
      - ./docker/volumes/nginx_secrets/:/etc/letsencrypt/

  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped
    command:
      - memcached
      - --memory-limit=${MEMCACHED_MEMORY}
      - --threads=${MEMCACHED_THREADS}
      # Uncomment to check for activity:
      # - -vv

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - ./docker/volumes/redis_data/:/data/

  celery:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./project/media/:/usr/src/app/project/media/
      - ./project/static/:/usr/src/app/project/static/:ro
    depends_on:
      - redis
      - memcached
    command:
      - celery
      - --app=project.celeryconf:app
      - worker
      - --loglevel=info
      - --beat

  ofelia:  # cron
    image: mcuadros/ofelia:v0.3.6
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:   # "real time labels reading is not supported yet"
      - django
    restart: unless-stopped
