version: "3.4"

services:
  db:
    image: "postgres:12-alpine"
    env_file: "ci_env"

  app-test:
    image: app-test
    env_file: "ci_env"
    depends_on:
      - db
    volumes:
      - test-artifacts:/usr/src/app/test-results

  # https://github.com/mozilla/normandy/blob/5eb2a4447ef3b6cf1b92c894d168b60702867eb4/ci/docker-compose.yml#L25-L32
  artifact-collector:
    image: debian:stable-slim
    volumes:
      - test-artifacts:/artifacts
    command: |
      bash -c "
        chmod -R 777 /artifacts
        echo Waiting for artifacts
        sleep 1h  # Wait a long time
      "

volumes:
  test-artifacts:
