version: '3.8'
services:
  postgres:
    build:
      context: postgres
    env_file: "ci_env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: ..
      target: test
    env_file: "ci_env"
    depends_on:
      - postgres
      - artifact-collector
    volumes:
      - test-artifacts:/usr/src/app/test-results

  artifact-collector:
    image: busybox:stable
    volumes:
      - test-artifacts:/artifacts
    init: true
    command: |
      sh -c "
        chmod -R 777 /artifacts
        echo Waiting for artifacts
        sleep inf  # Wait a long time
      "

volumes:
  test-artifacts:
