services:
  postgres:
    build:
      context: postgres
    env_file: "ci_env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: ..
      target: test
      args:
        HOST_UID: "${HOST_UID:-2640}"
        HOST_GID: "${HOST_GID:-2640}"
        WHO: "${WHO:-magnet}"
    env_file: "ci_env"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../.git:/usr/src/app/.git
      - ../test-results:/usr/src/app/test-results
