# Generated by Django 4.2.8 on 2024-04-24 14:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="version",
            field=models.PositiveSmallIntegerField(verbose_name="version"),
        ),
    ]
