# Generated by Django 4.2.8 on 2024-04-25 19:43

from django.db import migrations
from django.db import models

import base.fields.base
import base.fields.functions


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_alter_documentversion_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evidence",
            name="document_version",
        ),
        migrations.AddField(
            model_name="evidence",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="file",
            field=base.fields.base.BaseFileField(
                blank=True,
                null=True,
                upload_to=base.fields.functions.file_path,
                verbose_name="file",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("file__isnull", False), ("url__isnull", False), _connector="XOR"
                ),
                name="file_xor_url",
            ),
        ),
    ]
