# Generated by Django 4.2.8 on 2024-04-29 14:24

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0003_remove_evidence_document_version_evidence_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="control",
            options={
                "ordering": ("category", "title"),
                "verbose_name": "control",
                "verbose_name_plural": "controls",
            },
        ),
        migrations.AlterModelOptions(
            name="controlcategory",
            options={
                "ordering": ("name",),
                "verbose_name": "control category",
                "verbose_name_plural": "control categories",
            },
        ),
        migrations.RemoveConstraint(
            model_name="evidence",
            name="file_xor_url",
        ),
        migrations.AddField(
            model_name="documentversion",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="approved at"
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_document_versions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="url",
            field=models.URLField(blank=True, verbose_name="url"),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("file__isnull", True), ("file", ""), _connector="OR"),
                    models.Q(("url__isnull", True), ("url", ""), _connector="OR"),
                    _connector="XOR",
                ),
                name="file_xor_url",
                violation_error_message="An evidence must have a file or a url, but not both.",
            ),
        ),
    ]
