# Generated by Django 4.2.8 on 2024-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_controlcategory_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentversion",
            options={
                "ordering": ("-version",),
                "verbose_name": "document version",
                "verbose_name_plural": "document versions",
            },
        ),
    ]
