# Generated by Django 4.2.8 on 2024-04-05 11:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_documentversion_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentversion",
            name="shasum",
            field=models.CharField(max_length=64, verbose_name="shasum"),
        ),
    ]
