# Generated by Django 4.2.8 on 2024-05-01 16:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "documents",
            "0004_alter_control_options_alter_controlcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="control",
            name="document",
        ),
        migrations.AddField(
            model_name="control",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="controls",
                to="documents.document",
                verbose_name="documents",
            ),
        ),
    ]
