# Generated by Django 4.2.8 on 2024-05-02 02:08

import django.core.validators

from django.db import migrations
from django.db import models


def apply_migration(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    for document in Document.objects.all():
        document.code = f"DOC{document.id}"
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_remove_control_document_control_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="code",
            field=models.CharField(default="", max_length=20, verbose_name="code"),
            preserve_default=False,
        ),
        migrations.RunPython(apply_migration, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="document",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="The code must have between 3 and 20 uppercase characters and be unique.",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code doesn't comply with required format.",
                        regex="[A-ZÑ\\d]{3,20}",
                    )
                ],
                verbose_name="code",
            ),
        ),
    ]
