# Generated by Django 4.2.8 on 2024-04-10 15:14

import django.db.models.deletion

from django.db import migrations
from django.db import models

import base.fields.base
import base.fields.functions
import base.mixins


class Migration(migrations.Migration):

    dependencies = [
        (
            "processes",
            "0002_remove_processactivitydefinition_asignee_xor_asignee_group_and_more",
        ),
        ("documents", "0005_alter_documentversion_shasum"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                (
                    "file",
                    base.fields.base.BaseFileField(
                        upload_to=base.fields.functions.file_path, verbose_name="file"
                    ),
                ),
                ("shasum", models.CharField(max_length=64, verbose_name="shasum")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="processes.processactivity",
                        verbose_name="activity",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidences",
                        to="documents.documentversion",
                        verbose_name="document version",
                    ),
                ),
            ],
            options={
                "verbose_name": "evidence",
                "verbose_name_plural": "evidences",
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
    ]
