# Generated by Django 4.2.8 on 2024-04-12 14:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_evidence"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evidence",
            old_name="activity",
            new_name="process_activity",
        ),
        migrations.AlterField(
            model_name="control",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=255, unique=True, verbose_name="title"),
        ),
        migrations.AddConstraint(
            model_name="documentreadbyuser",
            constraint=models.UniqueConstraint(
                fields=("document_version", "user"), name="unique_document_read_by_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "version"), name="unique_document_version"
            ),
        ),
    ]
