# Generated by Django 4.2.8 on 2024-05-03 23:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0006_document_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ("title",),
                "verbose_name": "document",
                "verbose_name_plural": "documents",
            },
        ),
        migrations.RemoveField(
            model_name="control",
            name="documents",
        ),
        migrations.AddField(
            model_name="document",
            name="documented_controls",
            field=models.ManyToManyField(
                blank=True,
                related_name="documented_in",
                to="documents.control",
                verbose_name="documented controls",
            ),
        ),
    ]
