# Generated by Django 4.2.8 on 2024-05-03 23:39

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0007_alter_document_options_remove_control_documents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="approval_evidence",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_document_version",
                to="documents.evidence",
                verbose_name="approval evidence",
            ),
        ),
    ]
