# Generated by Django 4.2.8 on 2024-04-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_control_created_by_control_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentversion",
            options={
                "ordering": ("-version",),
                "permissions": (
                    ("approve_documentversion", "Can approve document version"),
                ),
                "verbose_name": "document version",
                "verbose_name_plural": "document versions",
            },
        ),
    ]
