# Generated by Django 4.2.13 on 2024-06-03 21:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0009_alter_documentversion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="drive_folder",
            field=models.URLField(blank=True, verbose_name="drive folder"),
        ),
    ]
