# Generated by Django 4.2.13 on 2024-06-06 19:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0010_document_drive_folder"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="evidence",
            name="file_xor_url",
        ),
        migrations.AddField(
            model_name="evidence",
            name="text",
            field=models.TextField(blank=True, verbose_name="text"),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(("file", ""), _negated=True), ("url", ""), ("text", "")
                    ),
                    models.Q(
                        ("file", ""), models.Q(("url", ""), _negated=True), ("text", "")
                    ),
                    models.Q(
                        ("file", ""), ("url", ""), models.Q(("text", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="file_url_or_text",
                violation_error_message="An evidence must have either a file, a url or text.",
            ),
        ),
    ]
