# Generated by Django 4.2.13 on 2024-06-10 21:50

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models

import base.fields.base
import base.fields.functions


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0011_remove_evidence_file_xor_url_evidence_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_document_versions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="file_url",
            field=models.URLField(blank=True, verbose_name="file url"),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="file",
            field=base.fields.base.BaseFileField(
                blank=True,
                upload_to=base.fields.functions.file_path,
                verbose_name="file",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                check=models.Q(("file", ""), ("file_url", ""), _connector="XOR"),
                name="file_xor_file_url",
                violation_error_message="Either file or file url must be set",
            ),
        ),
    ]
