# Generated by Django 4.2.13 on 2024-06-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_documenttype_document_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttype",
            options={
                "verbose_name": "document type",
                "verbose_name_plural": "document types",
            },
        ),
    ]
