# Generated by Django 3.2.18 on 2023-05-18 15:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("error", models.TextField(verbose_name="error")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        verbose_name="method",
                    ),
                ),
                ("url", models.TextField(verbose_name="url")),
                ("endpoint", models.TextField(verbose_name="endpoint")),
                ("client_url", models.TextField(verbose_name="client url")),
                ("client_code", models.TextField(verbose_name="client code")),
                (
                    "request_time",
                    models.DateTimeField(
                        help_text="request time", null=True, verbose_name="request time"
                    ),
                ),
                ("request_headers", models.TextField(verbose_name="headers")),
                ("request_content", models.TextField(verbose_name="content")),
                (
                    "response_time",
                    models.DateTimeField(
                        help_text="response time",
                        null=True,
                        verbose_name="response time",
                    ),
                ),
                ("response_headers", models.TextField(verbose_name="headers")),
                ("response_content", models.TextField(verbose_name="content")),
                (
                    "response_status_code",
                    models.IntegerField(null=True, verbose_name="status code"),
                ),
            ],
        ),
    ]
