- name: restore DB dump
  hosts: all
  gather_facts: no
  tasks:

    - name: stop django
      # 'ERROR:  database "..." is being accessed by other users'
      command: docker compose stop django celery
      args:
        chdir: "{{ project_name }}"
      changed_when: true  # Unfortunately "Stopping"/"Stopped" are always printed

    - name: drop and create database
      command: docker compose exec postgres sh -c 'psql -c "{{ cmd1 }}" -c "{{ cmd2 }}" postgres'
      args:
        chdir: "{{ project_name }}"
      vars:
        cmd1: drop database if exists \"$PGDATABASE\";
        cmd2: create database \"$PGDATABASE\";

    - name: restore dump
      command: docker compose exec postgres bash -c '{{ restore_cmd }}'
      args:
        chdir: "{{ project_name }}"
      vars:
        restore_cmd: >
          pg_restore
          --dbname="$PGDATABASE"
          --no-owner
          --no-acl
          --jobs="{{ jobs }}"
          "db_dumps/{{ dump_name | quote }}"

        # man says: "A good place to start is the number of CPU cores on the server"
        # but if server is remote, just assume 1.
        jobs: $( {{ host_is_remote_test }} && echo 1 || nproc )

        # From magnet-entrypoint.sh:
        host_is_remote_test: '[[ "$PGHOST" != "localhost" && "$PGHOST" != "postgres" ]]'

    - name: start django
      # The entrypoint will run migrations
      command: docker compose start django celery
      args:
        chdir: "{{ project_name }}"
      changed_when: true
