- name: clone/pull repository
  git:
    repo: "{{ git_url }}"
    version: "{{ branch }}"
    dest: "{{ project_name }}"
  # Remotes are sometimes flaky, so:
  register: git_result
  retries: 2
  delay: 5
  until: git_result is succeeded

- name: backup DB on code change
  debug:
    msg: "TODO: backup DB"
  when: git_result.changed
