# Generated by Django 3.2.18 on 2023-06-02 16:16

from django.db import migrations
from django.db import models

import base.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="creation date",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="edition date",
                        null=True,
                        verbose_name="updated at",
                    ),
                ),
                ("raw_value", models.TextField(verbose_name="value")),
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=50, unique=True, verbose_name="name"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("int", "integer"),
                            ("float", "float"),
                            ("time", "time"),
                            ("date", "date"),
                            ("json", "json"),
                            ("url", "url"),
                            ("hostname", "host name"),
                            ("ip_network", "IP prefix/range"),
                            ("hostname_list", "host name list"),
                            ("ip_network_list", "IP prefix/range list"),
                            ("bool", "boolean"),
                            ("str", "text"),
                        ],
                        editable=False,
                        max_length=255,
                        verbose_name="kind",
                    ),
                ),
                (
                    "cache_seconds",
                    models.PositiveIntegerField(
                        default=3600, verbose_name="cache seconds"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(base.mixins.AuditMixin, models.Model),
        ),
    ]
