- name: set dump_name
  set_fact:
    dump_name: "{{ ansible_limit }}-{{ cur_date }}.dump"
  vars:
    # This runs in controller, faster than gathering remote facts:
    cur_date: "{{ lookup('pipe', 'date --utc +%Y-%m-%d_%H-%M-%S') }}"

- name: run pg_dump
  # Just use "docker compose exec ..."
  # https://github.com/v4dkou/ansible-remote-docker tried to do it the nice way
  # (ansible controlling container instead of host), but with unreliable results.
  command: docker compose exec postgres pg_dump --format=custom --file=/db_dumps/{{ dump_name }}
  args:
    chdir: "{{ project_name }}"
  changed_when: true
